version: "3.9"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        ports:
            - ${FE_PORT}:${FE_PORT}
        restart: unless-stopped # otherwise there is no manual control over it
        depends_on:
            - backend
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        environment:
            - BE_PORT=${BE_PORT}
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - ${BE_PORT}:${BE_PORT}
    db:
        container_name: db
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - INIT_WAIT_SEC=${INIT_WAIT_SEC}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
