version: "3.9"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - SERVER_URL=${SERVER_URL}
      - API_URL=${API_URL}
    ports:
      - ${FE_PORT}:${FE_PORT}
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    container_name: backend
    build: 
      context: ./backend
    environment:
      - BE_DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SA_EMAIL=${SA_EMAIL}
      - SA_PASSWORD=${SA_PASSWORD}
      - BE_PORT=${BE_PORT}
      - FE_PORT=${FE_PORT}
      - REDIS_PORT=${REDIS_PORT}
    ports: 
      - ${BE_PORT}:${BE_PORT}
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - INIT_WAIT_SEC=${INIT_WAIT_SEC}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data:/data/db

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
    mongodb_data:
